### ISSUE TITLE
[1.16.2][1.0.0] Crashes when a structure is being generated with a Campfire or Sign

### ISSUE THREAD

**Issue by TelepathicGrunt** [Gunpowder-MC/GunpowderSleepVote#1]
This crash is easily reproducible by putting on Repurposed Structures and going to either a Stone Igloo or Mountains Village and the game will crash as these two structures contains a Campfire. You could probably recreate this without my mod in Vanilla by using a datapack to replace and igloo piece and give it a campfire. Though the vanilla igloo should also cause the crash too as they have a Sign and this crash report mentions a Sign. It's strange. 

The crash does not happen when only SleepVote is removed but will happen when it is added and a structure is made during worldgen with certain block entities

Logs:
https://hatebin.com/askyrkqmin
[latest.log](https://github.com/Gunpowder-MC/GunpowderSleepVote/files/5078159/latest.log)

The crash this time seems to be 
Structure.place -> SignBlockEntity.markDirty 

I can't remember which mod makes the crash report much better but if you know it, let me know and I'll recreate the crash with the mod to give a better log report

**Comment by TelepathicGrunt** [comment]
Here's a datapack to recreate the crash without needing any other mod except for Gunpower and Sleepvote. Put this datapack into a world's datapack folder and the do /reload if you haven't restarted the game. Then do /locate igloo and teleport to it in order to crash. 

I basically shoved a bunch of block entities into the top piece of vanilla igloo.
[modified_igloo.zip](https://github.com/Gunpowder-MC/GunpowderSleepVote/files/5078648/modified_igloo.zip)

**Comment by Martmists-GH** [comment]
Fixed, install Gunpowder 0.2.9 patch 1 or above.
