### ISSUE TITLE
1.16.1 Sleepvote prevents gamerules from being saved.

### ISSUE THREAD

**Issue by ghost** [Gunpowder-MC/GunpowderSleepVote#2]
This obviously isn't an issue any more with the gunpowder version, but I wanted to report it anyway.
Large packs like AOF3 are using sleepvote, and are likely not able to update to 1.16.2 any time soon.

https://pastebin.com/hqF8LSik

If I can provide further logs or testing, please let me know.  This test was done on a fresh server setup.

**Comment by Martmists-GH** [comment]
We don't offer support for 1.16.1 anymore.
