### ISSUE TITLE
Entity AI/movement breaks?

### ISSUE THREAD

**Issue by DyonR** [Gunpowder-MC/GunpowderSleepVote#3]
Before implementing this mod to my server, I was testing around to see if it functions as desired.
But I ran into quite an odd issue.
If I enter spectator mode, or creative mode and fly far away, let's say 1000 blocks, all mobs, items and other entities seem to have lost their AI. Using spawn eggs to spawn zombies and setting the time to day, does not make them catch fire, move or anything else. Punching them does nothing. Foxes do not run away from players. Dropped items visually get stuck into the air, gravity affected blocks do not fall.  
  
If the player relogs, everything in that area works fine again, till moving far away.  

If I remove the SleepVote module everythings works fine.  
The other mods I have installed are:  
fabric-api-0.22.0+build.408-1.16
fabric-language-kotlin-1.4.0+build.1
gunpowder-base-0.2.10+1.16.2

**Comment by DyonR** [comment]
I've also uploaded a demo to YouTube: https://youtu.be/T0i46UVTMmQ

**Comment by Martmists-GH** [comment]
Unable to reproduce. Make sure absolutely no other mods are installed.

**Comment by DyonR** [comment]
I am able to reproduce this 100% of the times myself, I tried it on Singleplayer with Fabric 0.9.3+build.207-1.16.2 (Java 14) as well on a Fabric server (other PC than my Singleplayer) running Fabric 0.10.0+build.208 (OpenJRE 8).  
Absolutely no other mods are installed, besides the ones I listed.  
I find it very odd also
