### ISSUE TITLE
Implement a fix for MC-63340

### ISSUE THREAD

**Issue by DyonR** [Gunpowder-MC/GunpowderSleepVote#5]
Not sure if possible, but just suggesting;
Would it be possible to implement a fix for MC-63340 in this module?  
https://bugs.mojang.com/browse/MC-63340  
  
Since this kinda changes vanilla behaviour, having this as a setting in the `gunpowder-sleepvote.yaml` as, for example, `fixmc63340` would be nice

**Comment by Martmists-GH** [comment]
This should be a separate mod instead.
